version: '3.1'

services:

  pgdb:
    image: postgres
    container_name: postgres-btp
    ports:
      - 5432:5432
    volumes:
      - /home/ubuntu/node-deployment/.data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dashboard
      POSTGRES_PASSWORD: dashboard

  pgadmin:
    image: dpage/pgadmin4
    container_name: postgres-admin-btp
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: test123
