version: '3.1'

services:

  pgdb:
    image: postgres
    container_name: postgres-btp
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: postgres-admin-btp
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: test123
